#!/usr/bin/env python3
"""Generate Android vectors from the approved sail-in-O wordmark. No fonts required."""
from copy import deepcopy
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "design/brand"
OUT = ROOT / "core/design/src/main/res/drawable"
ANDROID = "http://schemas.android.com/apk/res/android"
SVG = "http://www.w3.org/2000/svg"
ET.register_namespace("android", ANDROID)
ET.register_namespace("", SVG)
def a(name): return "{" + ANDROID + "}" + name

def main():
    master = ET.parse(SOURCE / "yokuli-wordmark.svg").getroot()
    paths = list(master.iter("{" + SVG + "}path"))
    by_id = {p.attrib["id"]: p for p in paths}
    required = {"letters", "ring", "sail", "wake", "os"}
    if set(by_id) != required:
        raise ValueError("The approved wordmark needs letters, ring, sail, wake and os paths")
    mark = [by_id[key] for key in ("ring", "sail", "wake")]
    OUT.mkdir(parents=True, exist_ok=True)

    def vector(name, dimensions, viewport, geometry, scale=1, dx=0, dy=0, light=False, mono=False, background=None):
        root = ET.Element("vector", {a("width"):f"{dimensions[0]}dp", a("height"):f"{dimensions[1]}dp",
            a("viewportWidth"):str(viewport[0]), a("viewportHeight"):str(viewport[1])})
        if background:
            ET.SubElement(root, "path", {a("fillColor"):background, a("pathData"):f"M0 0H{viewport[0]}V{viewport[1]}H0Z"})
        group = ET.SubElement(root, "group", {a("scaleX"):str(scale), a("scaleY"):str(scale),
            a("translateX"):str(dx), a("translateY"):str(dy)})
        for p in geometry:
            fill = p.attrib["fill"]
            if mono or light and p.attrib["id"] in ("letters", "ring"):
                fill = "#FAF9F6"
            elif light and p.attrib["id"] == "os":
                fill = "#B4BFBE"
            ET.SubElement(group, "path", {a("name"):p.attrib["id"], a("fillColor"):fill,
                a("fillType"):"evenOdd" if p.attrib.get("fill-rule") == "evenodd" else "nonZero",
                a("pathData"):" ".join(p.attrib["d"].split())})
        ET.indent(root, space="    ")
        (OUT / f"{name}.xml").write_text('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/generate_brand_assets.py; edit the SVG master. -->\n' + ET.tostring(root, encoding="unicode") + '\n', encoding="utf-8")

    # All small marks are an extraction of the same O, not a second brand design.
    vector("yokuli_mark_body", (64,64), (64,64), [by_id["ring"]], .2, -30, 8)
    vector("yokuli_mark_beacon", (64,64), (64,64), [by_id["sail"],by_id["wake"]], .2, -30, 8)
    vector("yokuli_wordmark", (218,58.8), (1090,294), paths)
    vector("yokuli_wordmark_body", (218,58.8), (1090,294), [by_id["letters"],by_id["ring"]])
    vector("yokuli_wordmark_sail", (218,58.8), (1090,294), [by_id["sail"],by_id["wake"]])
    vector("yokuli_wordmark_os", (218,58.8), (1090,294), [by_id["os"]])
    # Visible outline stays inside the launcher mask's central safe circle.
    vector("yokuli_launcher_foreground", (108,108), (108,108), mark, .16, 5.04, 35.04, light=True)
    vector("yokuli_launcher_monochrome", (108,108), (108,108), mark, .16, 5.04, 35.04, mono=True)
    vector("yokuli_legacy_icon", (108,108), (108,108), mark, .16, 5.04, 35.04, light=True, background="#1F2A30")
    vector("yokuli_splash_symbol", (288,288), (96,96), mark, .16, -.96, 29.04, light=True)
    vector("yokuli_splash_wordmark", (200,80), (200,80), paths, .176, 4.08, 14.128, light=True)
    compact = ET.Element("{"+SVG+"}svg", {"width":"320", "height":"240", "viewBox":"150 0 320 240"})
    ET.SubElement(compact, "{"+SVG+"}title").text = "YOKULI OS — sail-in-O compact mark"
    compact.extend(deepcopy(p) for p in mark)
    ET.indent(compact, space="  ")
    (SOURCE / "yokuli-mark.svg").write_text(ET.tostring(compact, encoding="unicode")+'\n', encoding="utf-8")
    (SOURCE / "yokuli-os.svg").write_text((SOURCE / "yokuli-wordmark.svg").read_text(encoding="utf-8"), encoding="utf-8")
    print("Generated 11 production vectors and two derived SVG assets")

if __name__ == "__main__":
    main()
