#!/usr/bin/env python3
"""Generate production vectors and pixel geometry from the two original SVG masters."""
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "design/brand"
OUT = ROOT / "core/design/src/main/res/drawable"
ANDROID = "http://schemas.android.com/apk/res/android"
SVG = "http://www.w3.org/2000/svg"
ET.register_namespace("android", ANDROID)
ET.register_namespace("", SVG)
def a(name): return "{" + ANDROID + "}" + name

def main():
    wordmark = ET.parse(SOURCE / "yokuli-wordmark.svg").getroot()
    lettering = list(wordmark.iter("{" + SVG + "}path"))
    by_id = {p.attrib["id"]: p for p in lettering}
    if set(by_id) != {"letters", "os"}:
        raise ValueError("The lowercase wordmark requires letters and os outlines")
    symbol = ET.parse(SOURCE / "yokuli-mark.svg").getroot()
    mark, cells = [], []
    for group in symbol.findall("{" + SVG + "}g"):
        rectangles = []
        for rectangle in group:
            x, y, width, height = (int(rectangle.attrib[k]) for k in ("x", "y", "width", "height"))
            if min(x,y) < 0 or min(width,height) <= 0 or max(x+width,y+height) > 16:
                raise ValueError("Pixel sail geometry must stay on its sixteen-cell grid")
            cells.append((x,y,width,height,group.attrib["id"] == "sail"))
            rectangles.append(f"M{x} {y}h{width}v{height}h{-width}Z")
        mark.append(ET.Element("path", {"id":group.attrib["id"],"fill":"#111111","d":" ".join(rectangles)}))

    def vector(name, dimensions, viewport, geometry, scale=1, dx=0, dy=0, white=False, background=None, out=OUT):
        root = ET.Element("vector", {a("width"):f"{dimensions[0]}dp", a("height"):f"{dimensions[1]}dp",
            a("viewportWidth"):str(viewport[0]), a("viewportHeight"):str(viewport[1])})
        if background:
            ET.SubElement(root, "path", {a("fillColor"):background, a("pathData"):f"M0 0H{viewport[0]}V{viewport[1]}H0Z"})
        group = ET.SubElement(root, "group", {a("scaleX"):str(scale), a("scaleY"):str(scale),
            a("translateX"):str(dx), a("translateY"):str(dy)})
        for p in geometry:
            ET.SubElement(group, "path", {a("name"):p.attrib["id"],a("fillColor"):"#FFFFFF" if white else p.attrib["fill"],
                a("fillType"):"evenOdd" if p.attrib.get("fill-rule") == "evenodd" else "nonZero",
                a("pathData"):" ".join(p.attrib["d"].split())})
        ET.indent(root, space="    ")
        out.mkdir(parents=True, exist_ok=True)
        (out / f"{name}.xml").write_text('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/generate_brand_assets.py; edit the SVG masters. -->\n' + ET.tostring(root, encoding="unicode") + '\n', encoding="utf-8")

    vector("yokuli_mark_body", (32,32), (16,16), [mark[1]])
    vector("yokuli_mark_beacon", (32,32), (16,16), [mark[0]])
    vector("yokuli_wordmark", (208,48), (312,72), lettering)
    vector("yokuli_wordmark_body", (208,48), (312,72), [by_id["letters"]])
    vector("yokuli_wordmark_os", (208,48), (312,72), [by_id["os"]])
    # The whole sixteen-cell symbol fits Android's adaptive-icon safe circle.
    vector("yokuli_launcher_foreground", (108,108), (108,108), mark, 3, 30, 30, white=True)
    vector("yokuli_launcher_monochrome", (108,108), (108,108), mark, 3, 30, 30, white=True)
    vector("yokuli_legacy_icon", (108,108), (108,108), mark, 3, 30, 30, white=True, background="#111111")
    vector("yokuli_splash_symbol", (288,288), (288,288), mark, 3, 120, 120, white=True)
    vector("yokuli_splash_wordmark", (200,80), (200,80), lettering, .5, 22, 22, white=True)
    vector("ic_yokuli_notice", (24,24), (16,16), mark, white=True,
        out=ROOT / "runtime/marine-local/src/main/res/drawable")
    # Geometry is generated from the same SVG, so Canvas can snap every block to physical pixels.
    geometry = ROOT / "core/design/src/main/java/com/yokuli/marine/core/design/YokuliPixelGeometry.kt"
    geometry.write_text("package com.yokuli.marine.core.design\n\n// Generated from design/brand/yokuli-mark.svg; do not edit.\ninternal data class BrandPixel(val x:Int,val y:Int,val width:Int,val height:Int,val sail:Boolean)\ninternal val yokuliPixelSail = listOf(\n" +
        ",\n".join(f"    BrandPixel({x},{y},{w},{h},{str(s).lower()})" for x,y,w,h,s in cells) + "\n)\n", encoding="utf-8")
    (SOURCE / "yokuli-os.svg").write_text((SOURCE / "yokuli-wordmark.svg").read_text(encoding="utf-8"), encoding="utf-8")
    # Obsolete layered sail-in-O resource must never reappear through an old caller.
    obsolete = OUT / "yokuli_wordmark_sail.xml"
    if obsolete.exists(): obsolete.unlink()
    print("Generated eleven production vectors, shared pixel geometry and derived wordmark")

if __name__ == "__main__":
    main()
