package com.yokuli.anchorwatch

import androidx.activity.OnBackPressedDispatcher
import androidx.activity.OnBackPressedDispatcherOwner
import androidx.activity.compose.BackHandler
import androidx.activity.compose.LocalOnBackPressedDispatcherOwner
import androidx.lifecycle.compose.LocalLifecycleOwner
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.pager.HorizontalPager
import androidx.compose.foundation.pager.PagerScope
import androidx.compose.foundation.pager.rememberPagerState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.yokuli.anchorwatch.domain.model.AppLanguage
import com.yokuli.anchorwatch.ui.theme.YokuliTheme
import kotlinx.coroutines.launch

internal val LocalMarineEmbeddedRoot=compositionLocalOf { false }
internal val LocalMarineSubpageTitle=compositionLocalOf<MutableState<String?>?> { null }

@Composable internal fun MarineSubpageTitle(title:String) {
    val holder=LocalMarineSubpageTitle.current
    DisposableEffect(holder,title) { holder?.value=title; onDispose { if(holder?.value==title)holder.value=null } }
}

/** Business destinations are embedded in the Shell; there is no second launcher,
 * activity, bottom navigation bar or independently owned connection state. */
@Composable
fun LegacyMarineScreen(
    destination: String,
    vm: MainViewModel,
    chinese: Boolean,
    accent: Color,
    light: Boolean,
    onBack: () -> Unit,
    onBackHandler: ((() -> Boolean)?) -> Unit = {},
) {
    val state by vm.ui.collectAsState()
    val language = if (chinese) AppLanguage.SIMPLIFIED_CHINESE else AppLanguage.ENGLISH
    val cockpit = remember { mutableStateOf(false) }
    val subpageTitle=remember(destination){mutableStateOf<String?>(null)}
    var nestedDestination by remember(destination) { mutableStateOf<String?>(null) }
    LaunchedEffect(vm,destination) {
        vm.navigationRequests.collect { page -> nestedDestination = when(page) { 0 -> "anchor"; 1 -> "trip"; 2 -> when(vm.ui.value.dataSection){1->"nmea";2->"output";3->"sonar";else->"sources"}; else -> "marine-settings" } }
    }
    val lifecycleOwner=LocalLifecycleOwner.current
    val dispatcher=remember { OnBackPressedDispatcher() }
    val dispatcherOwner=remember(lifecycleOwner,dispatcher) { object:OnBackPressedDispatcherOwner {
        override val lifecycle=lifecycleOwner.lifecycle
        override val onBackPressedDispatcher=dispatcher
    } }
    val registerBack by rememberUpdatedState(onBackHandler)
    DisposableEffect(dispatcher) {
        registerBack { if(dispatcher.hasEnabledCallbacks()) { dispatcher.onBackPressed(); true } else false }
        onDispose { registerBack(null) }
    }
    // All underlying dialogs, reports, share cards and service notices follow
    // the Shell language, including non-composable strings generated by VM.
    LaunchedEffect(state.settingsReady, language) {
        if (state.settingsReady && state.settings.appLanguage != language) vm.updateSettings(state.settings.copy(appLanguage = language))
    }
    val current = nestedDestination ?: destination
    val back = { if(dispatcher.hasEnabledCallbacks()) dispatcher.onBackPressed() else onBack() }
    YokuliTheme(accent = accent, light = light) {
        CompositionLocalProvider(LocalAppLanguage provides language, LocalSailCockpitMode provides cockpit, LocalOnBackPressedDispatcherOwner provides dispatcherOwner, LocalMarineEmbeddedRoot provides true, LocalMarineSubpageTitle provides subpageTitle) {
            BackHandler(enabled=nestedDestination!=null || cockpit.value) { if(cockpit.value)cockpit.value=false else nestedDestination=null }
            Column(Modifier.fillMaxSize().background(MaterialTheme.colorScheme.background)) {
                if (!cockpit.value) MarinePageTitle(subpageTitle.value ?: when(current) {
                    "anchor" -> tr("anchor watch", "锚警报")
                    "trip" -> tr("sailing", "航行")
                    "anchorages" -> tr("anchorages", "锚地")
                    "sonar" -> tr("personal sonar", "个人声呐")
                    "voyages" -> tr("voyages", "航程")
                    "instruments" -> tr("instruments", "仪表")
                    "nmea" -> "nmea"
                    "output" -> tr("nmea output", "nmea 输出")
                    "sources" -> tr("vessel sources", "船舶数据源")
                    else -> tr("boat settings", "船舶设置")
                }, back)
                Box(Modifier.weight(1f)) {
                    val fullscreen = state.anchorageApproach.target != null || state.tripMapDestination != null
                    AppDestinationLayer(fullscreen, Modifier.fillMaxSize(), workspace = {
                        when(current) {
                            "anchor" -> MarinePivot(listOf(tr("watch", "当前"), tr("history", "历史"), tr("anchorages", "锚地")), state.anchorSection, vm::rememberAnchorSection) { page ->
                                when(page) { 0 -> AnchorWatchPage(state,vm); 1 -> AnchorHistoryPage(state,vm); else -> AnchorageLibraryPage(state,vm) }
                            }
                            "trip" -> MarinePivot(listOf(tr("live", "实时"),tr("voyages", "航程")), state.sailSection, vm::rememberSailSection) { page -> if(page==0) TripWatchPage(state,vm) else TripHistoryPage(state,vm) }
                            "anchorages" -> AnchorageLibraryPage(state,vm)
                            "sonar" -> SonarSurveyPage(state,vm)
                            "voyages" -> TripHistoryPage(state,vm)
                            "instruments" -> TripWatchPage(state,vm)
                            "nmea" -> MarinePivot(listOf(tr("connection", "连接"),tr("output", "输出"),tr("raw data", "原始数据"))) { page -> when(page) { 0 -> ConnectionPage(state,vm); 1 -> DataOutputSettingsPage(state,vm); else -> NmeaDataPage(state,vm) } }
                            "output" -> DataOutputSettingsPage(state,vm)
                            "sources" -> VesselDataSourcesPage(state,vm)
                            else -> SettingsScreen(state,vm)
                        }
                    }, fullscreenHost = { AnchorageApproachDestinationHost(state,vm); MarineTripMapDestinationHost(state,vm) })
                }
            }
        }
    }
}

@Composable
internal fun MarinePageTitle(title: String, back: () -> Unit) {
    Column(Modifier.fillMaxWidth().padding(start=20.dp,end=16.dp,top=10.dp,bottom=12.dp)) {
        Box(Modifier.size(34.dp).border(2.dp, MaterialTheme.colorScheme.onBackground, CircleShape).clickable(onClick=back),contentAlignment=Alignment.Center) {
            Icon(Icons.AutoMirrored.Filled.ArrowBack, tr("Back", "返回"), Modifier.size(24.dp))
        }
        Text(title, fontSize=46.sp, lineHeight=52.sp, fontWeight=FontWeight.Light, modifier=Modifier.padding(top=9.dp))
    }
}

@Composable
internal fun MarinePivot(titles: List<String>, initialPage:Int=0, onPage:(Int)->Unit={}, content:@Composable PagerScope.(Int)->Unit) {
    val pager=rememberPagerState(initialPage=initialPage.coerceIn(titles.indices),pageCount={titles.size})
    val scope=rememberCoroutineScope()
    LaunchedEffect(pager.currentPage) { onPage(pager.currentPage) }
    Column(Modifier.fillMaxSize()) {
        Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()).padding(start=20.dp,end=20.dp,bottom=12.dp),horizontalArrangement=Arrangement.spacedBy(26.dp)) {
            titles.forEachIndexed { index,title ->
                Text(title,fontSize=28.sp,fontWeight=FontWeight.Light,color=if(pager.currentPage==index)MaterialTheme.colorScheme.onBackground else MaterialTheme.colorScheme.onSurfaceVariant,modifier=Modifier.clickable{scope.launch{pager.animateScrollToPage(index)}})
            }
        }
        HorizontalPager(state=pager,modifier=Modifier.weight(1f),beyondViewportPageCount=0,pageContent=content)
    }
}

/** Put this once above the Shell so audible alarms remain actionable in Chart,
 * Start and Settings as well as the Anchor application. */
@Composable
fun LegacyMarineAlerts(vm:MainViewModel,chinese:Boolean,accent:Color,light:Boolean) {
    val state by vm.ui.collectAsState()
    YokuliTheme(accent=accent,light=light) {
        CompositionLocalProvider(LocalAppLanguage provides if(chinese)AppLanguage.SIMPLIFIED_CHINESE else AppLanguage.ENGLISH) {
            Box(Modifier.fillMaxSize()) {
                AlarmTestBanner(state,vm,Modifier.align(Alignment.TopCenter))
                if(state.alarmSnapshot.type!=com.yokuli.anchorwatch.domain.model.AlarmType.ALARM_TEST) RuntimeFeedbackBanner(state,vm,Modifier.align(Alignment.TopCenter))
            }
            AnchorDragAlarmDialog(state,vm)
        }
    }
}
